name: deinterlace  # Remember to modify to suit your project name
channels: 
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - dvc
  - dvc-ssh
  - conda-lock

# Non-standard section listing target platforms for conda-lock, modify according to your needs:
platforms:
  - linux-64
